#!/usr/bin/env bash
set -euo pipefail

readonly scriptDir=$(dirname $0)
source $scriptDir/gamename.sh

readonly tmpDir=/tmp/update-github-$NAME
mkdir -p $tmpDir
trap "rm -rf $tmpDir" EXIT

git clone bzr::http://code.alaiwan.org/bzr/games/$NAME $tmpDir/repo
cd $tmpDir/repo
git remote add github git@github.com:Ace17/$NAME.git
#git checkout -b master
git push -f github master
