#!/usr/bin/env bash
set -euo pipefail

set -x

readonly name="voiid"

readonly tmpDir=/tmp/update-github-$name
mkdir -p $tmpDir
trap "rm -rf $tmpDir" EXIT

git clone bzr::http://code.alaiwan.org/bzr/games/$name $tmpDir/repo
cd $tmpDir/repo
git remote add github git@github.com:Ace17/voiid.git
git checkout -b master
git push -f github master
