#!/usr/bin/env bash

set -euo pipefail

readonly scriptDir="$(dirname $0)"

readonly input=$1
readonly output3ds=$2
readonly outputPng=$3

export PYTHONPATH+=$scriptDir
blender "$input" --background \
  --python $scriptDir/convert_to_3ds_for_rendering.py \
  --python-exit-code \
  -- "$output3ds.tmp" "$outputPng.tmp" >/dev/null

# make the operation atomic
mv "$output3ds.tmp" "$output3ds"
mv "$outputPng.tmp" "$outputPng"

