#!/usr/bin/env bash

set -euo pipefail

readonly scriptDir="$(dirname $0)"

readonly input=$1
readonly output3ds=$2
readonly outputPng=$3

export PYTHONPATH+=$scriptDir
blender "$input" --background \
  --python $scriptDir/convert_to_3ds_for_rendering.py \
  --python-exit-code \
  -- "$output3ds" "$outputPng" >/dev/null

