#!/bin/bash
set -euo pipefail

readonly scriptDir=$(dirname $0)
source $scriptDir/gamename.sh

readonly tmpDir=/tmp/deliver-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p $tmpDir

function main
{
  echo "Delivering [$NAME]"
  make clean
  ./check
  deliverWindowsVersion
  #deliverWebVersion
}

function deliverWindowsVersion
{
  echo "-------------------------------------"
  echo "Building Windows version"
  BIN=$tmpDir/bin/w64 \
    ./scripts/w64-make -j`nproc` >/dev/null

  cp -a $tmpDir/bin/w64/rel                                        $tmpDir/$NAME
  cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll               $tmpDir/$NAME
  cp /usr/lib/gcc/x86_64-w64-mingw32/8.3-posix/libstdc++-6.dll     $tmpDir/$NAME
  cp /usr/lib/gcc/x86_64-w64-mingw32/8.3-posix/libgcc_s_seh-1.dll  $tmpDir/$NAME
  cp /opt/envs/win64/bin/SDL2.dll                                  $tmpDir/$NAME
  strip -s $tmpDir/$NAME/*.{exe,dll}

  cp -a res                                                        $tmpDir/$NAME

  (
    cd $tmpDir
    zip -q $NAME.zip -r $NAME
  )

  du -hs $tmpDir/$NAME.zip
  cp $tmpDir/$NAME.zip /tmp/
}

function deliverWebVersion
{
  echo "-------------------------------------"
  echo "Building Web version"
  BIN=bin/asmjs \
    scripts/asmjs-make -j`nproc` bin/asmjs/rel/game.html

  #------------------------------------------------------------------------------
  # create game directory
  #------------------------------------------------------------------------------
  readonly gameDir=$tmpDir/$NAME
  mkdir -p $gameDir

  cp -a bin/asmjs/rel/* $gameDir
  cp index.html $gameDir/index.html

  #------------------------------------------------------------------------------
  # archive it
  #------------------------------------------------------------------------------
  pushd $tmpDir
  zip $NAME.zip -r $NAME
  popd

  mv $tmpDir/$NAME.zip .

  #------------------------------------------------------------------------------
  # upload it to code.alaiwan.org
  #------------------------------------------------------------------------------
  rsync \
    --compress \
    --delete \
    -vr $gameDir/* alaiwans@code.alaiwan.org:public_html/games/$NAME
}

main
