#!/usr/bin/env bash

set -euo pipefail

readonly scriptDir="$(dirname $0)"

readonly input=$1
readonly outputMesh=$2

export PYTHONPATH+=$scriptDir
blender "$input" --background \
  --python $scriptDir/export_from_blender.py \
  --python-exit-code \
  -- "$outputMesh.tmp" >/dev/null

# make the operation atomic
mv "$outputMesh.tmp" "$outputMesh"

